name: Release Z-ui

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Setup Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 'stable'
          
      - name: Build z-ui
        run: |
          export CGO_ENABLED=1
          go build . -o zui-release
          
          mkdir z-ui
          cp zui-release z-ui/
          cp z-ui.service z-ui/
          cp z-ui.sh z-ui/
          mv z-ui/zui-release z-ui/z-ui
          mkdir z-ui/bin
          cd z-ui/bin
          
          # Download dependencies
          wget https://github.com/mhsanaei/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip Xray-linux-64.zip
          rm -f Xray-linux-64.zip
          rm -f geoip.dat geosite.dat iran.dat
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          wget https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
          wget https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran.dat
          mv xray ozip-linux-${{ matrix.platform }}
          cd ../..
          
      - name: Package
        run: tar -zcvf z-ui-linux-${{ matrix.platform }}.tar.gz z-ui
        
      - name: Upload
        uses: svenstaro/upload-release-action@2.6.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: z-ui-linux-${{ matrix.platform }}.tar.gz
          asset_name: z-ui-linux-${{ matrix.platform }}.tar.gz
          prerelease: true
          overwrite: true
